DISCORD_BOT_TOKEN = "MTM5NDY0ODQyMDI0NTA0OTQyNA.GR-FJv.aAhg1UAH0HKNP4eZdw7jyMuGt_poiZXXELq-rQ"
CASHEW_ENDPOINT = ""
CASHEW_TOKEN = ""
PERPLEXITY_API_KEY = "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"